### ISSUE TITLE
Translation for Oracle? 

### ISSUE THREAD

**Issue by smitsrr** [EMU-CFE/CanvasDataViewer#14]
First of all - thank you for your development work with the Canvas API!  We are in the middle of our data warehouse development initiative, and our institution's leadership is particularly interested in exploring our Canvas data. For all of the reasons you mention in the ReadMe, we need a way to automate the import from the API. 

However, our data warehouse sits on an Oracle database. Have you had experience in Oracle or know if there is an easy way to translate what you have done into an Oracle ecosystem? Thanks!

**Comment by 108-apps** [comment]
Hi smitsrr. At the moment, we only have the SqlServer version to offer. We were developing an analogous MySQL version, but that was shelved until further notice. Unfortunately, we don't have anything developed to translate and/or directly support an Oracle ecosystem developed at this time. 

Please let us know if you come across anything. We intend for the Canvas Data adventure to be as collaborative as possible and encourage as much input as possible.
