### ISSUE TITLE
No Data download

### ISSUE THREAD

**Issue by cdu-wv** [EMU-CFE/CanvasDataViewer#15]
I have downloaded and configured Dataviewer given in the document, given the parameters in the autoconfig.bat and created Canvas Datastore database and ran canvas data store scripts.
I executed dbo.CanvasData_General_DownloadSchemaAndTables procedure and I do not see any files downloaded or any error message. 
Can some one please point me where I am going wrong.
Thanks
cdu-wv

**Comment by 108-apps** [comment]
Hi cdu-wv,

Given your outline of the issue, its hard for me to determine exactly where the issue may be. Just of the top of my head; do you have the folders created with the appropriate permissions?
