### ISSUE TITLE
API or Redshift clarification

### ISSUE THREAD

**Issue by elearningdave** [EMU-CFE/CanvasDataViewer#24]
Our MIS people are looking at this, but we're looking for some clarification.
It mentions canvas data and API in the same sentence - to me, canvas data is 2 days old and not timely enough (fine for monthly management meetings, not for staff who want data that is maximum 1 day old) as well as API (realtime data, great, we love it).

Looking at your readme, it seems like it uses API calls to get the data that we had played with initially in Redshift. So not live data. Is that correct?

**Comment by benjamin-hudson** [comment]
I don't believe EMU is providing active support for this product, however your understanding seems correct. This uses API calls to download the schema and data files available to your organization, so the roughly 2 day old files.

**Comment by wjones20** [comment]
Dave, Benjamin -- Yes, you're correct.  This application is downloading the
flat files product for Canvas Data.  It's using APIs to do the download,
but that's not hitting live data in their database.  And I'd check the
documentation for the Amazon Redshift product too--it may be a little
fresher, but Canvas Data is still extracted and transformed, so it's
already aging compared to what you'd get from a direct API call or in the
GUI.  Thanks, Bill

*********************************************************
Bill Jones, MA, MS      Director, Instr Tech & Info Mngmt
Center for E-Learning                  ph: (734) 487-9043
Eastern Michigan University           fax: (734) 487-6695
Ypsilanti, MI 48197             email: wjones20@emich.edu
*********************************************************

**Comment by elearningdave** [comment]
Thanks for clarifying. I adapted some API code we had already, and built some SQL tables using it. MIS are taking a look at using that now.
